Config system
cameds58/ps2_ex4_config pull request #2
Opened 2024-11-04 22:23 UTC by ps2016-mt

2024-11-07 01:09 UTC, ty338jy commented on nba/config_classes.py
> +    another_file: str
Hey Pushpin @ps2016-mt,
I think the config_classes here doesn't match the config.yaml!
In config.yaml we have both class Data and class Model, which should be the same structure

2024-11-07 01:12 UTC, ty338jy commented on nba/config.py
> +from config_classes import DataPaths
Hey Pushpin @ps2016-mt , 
I think we might have a mismatch with config.yaml?
As config.yaml has data and model, config_classes should have  class Data and class Model, in config.py we should have 'from config_classes import Data, Model'

2024-11-08 01:05 UTC, ty338jy commented
Hello, well done! Test run successful, please merge!

2024-11-08 01:05 UTC, ty338jy approved these changes

2024-11-08 02:11 UTC, cameds58 approved these changes, later dismissed
looks good

2024-11-08 09:10 UTC, yuanjingshi requested changes
The environment yml file has a typo in its name and cannot setup environment.

2024-11-08 10:03 UTC, closed without merging